#!/usr/bin/env php
<?php
/**
 * Add any expected errors here.
 *
 * @see https://github.com/DaveLiddament/phpstan-php-language-extensions/blob/main/e2e/test-runner
 * @licence https://github.com/DaveLiddament/phpstan-php-language-extensions/blob/main/LICENSE.md
 *
 * Format:
 *
 * <file>:<line>:<identifier>
 *
 * Where:
 *
 * `file` is relative to the `build/e2e/data` directory.
 * `line` is the line number in the file.
 * `identifier` is the rule's identifier (NOTE: the prefix `phpExtensionLibrary.` is automatically added)
 */

require_once __DIR__ . '/../vendor/autoload.php';

$expectedErrors = [
    'lang/ja.json:2:lostInTranslation.possiblyUnusedTranslationString',
    'lang/ja/messages:2:lostInTranslation.possiblyUnusedTranslationString',
    'lang/zh.json:2:lostInTranslation.translationLoaderWarning',
    'lang/zh/messages:2:lostInTranslation.translationLoaderWarning',
    'src/dynamic-translation-string:5:lostInTranslation.dynamicTranslationString',
    'src/dynamic-translation-string:8:lostInTranslation.dynamicTranslationString',
    'src/invalid-choice:3:lostInTranslation.choiceMissingCase',
    'src/invalid-replacement:4:lostInTranslation.unusedReplacement',
    'src/invalid-replacement:4:lostInTranslation.unusedReplacement',
    'src/invalid-replacement:7:lostInTranslation.multipleReplaceVariants',
    'src/missing-translation-string:3:lostInTranslation.missingTranslationString',
    'src/missing-translation-string-in-base-locale:3:lostInTranslation.missingBaseLocaleTranslationString',
];

if (version_compare(\Composer\InstalledVersions::getVersion('tomasvotruba/bladestan'), '0.7', '<')) {
    $expectedErrors = array_merge($expectedErrors, [
        'src/blade:3:',
        'src/blade:3:',
        'src/blade:3:',
        'src/blade:3:',
        'src/blade:3:',
        'src/blade:3:',
        'src/blade:3:',
    ]);
} else {
    $expectedErrors = array_merge($expectedErrors, [
        'src/blade:3:lostInTranslation.missingTranslationString',
        'src/blade:3:lostInTranslation.missingTranslationString',
        'src/blade:3:lostInTranslation.missingTranslationString',
        'src/blade:3:lostInTranslation.missingTranslationString',
        'src/blade:3:lostInTranslation.missingTranslationString',
        'src/blade:3:lostInTranslation.missingTranslationString',
        'src/blade:3:lostInTranslation.missingTranslationString',
    ]);
}

/**
 * Main script.
 */
require_once __DIR__.'/PHPStanResultsChecker.php';
$phpStanResultsChecker = new PHPStanResultsChecker();
$stdIn = file_get_contents('php://stdin');

if (false === $stdIn) {
    echo "No input\n";
    exit(2);
}

try {
    $phpStanResultsChecker->checkResults($stdIn, $expectedErrors);
    echo "E2E tests OK\n";
    exit(0);
} catch (Exception $e) {
    echo $e->getMessage().\PHP_EOL;
    exit(1);
}
